%define major 0
%define libname %mklibname ytnef %major
%define devname %mklibname -d ytnef

Summary:	TNEF Stream Parser Library
Name:		libytnef
Version:	1.9.3
Release:	1
License:	GPLv2+
Group:		System/Libraries
Url:		https://github.com/Yeraze/ytnef/tree/master/ytnef
# Mismatch in version forces to use the master branch.
Source0:		https://github.com/Yeraze/ytnef/archive/ytnef-master.zip

Requires:	perl-MIME-tools
Requires:	%{libname} = %{version}-%{release}

%description
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %{libname}
Summary:	TNEF Stream Parser shared library
Group:		System/Libraries

%description -n %{libname}
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %{devname}
Summary:	TNEF Stream Parser library
Group:		Development/C
Requires:	%{libname} = %{version}-%{release}
Provides:	libytnef-devel = %{version}-%{release}

%description -n %{devname}
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%prep
%setup -q -n ytnef-master

%build
NOCONFIGURE=1 ./autogen.sh
%configure
%make_build

%install
%make_install

%files -n %{libname}
%{_libdir}/libytnef.so.%{major}*

%files -n %{devname}
%doc ChangeLog
%{_libdir}/libytnef.so
%{_includedir}/*.h

