%define name libytnef
%define version 1.5
%define release %mkrel 7

%define major 0
%define libname %mklibname ytnef %major
%define develname %mklibname -d ytnef

Summary: TNEF Stream Parser Library
Name: %{name}
Version: %{version}
Release: %{release}
Source0: http://downloads.sourceforge.net/ytnef/%{name}-%{version}.tar.bz
License: GPLv2+
Group: System/Libraries
Url: http://ytnef.sourceforge.net/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot

%description
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %libname
Summary: TNEF Stream Parser shared library
Group: System/Libraries

%description -n %libname
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %develname
Summary: TNEF Stream Parser library
Group: Development/C
Requires: %libname = %version
Provides: libytnef-devel = %version-%release

%description -n %develname
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.


%prep
%setup -q

%build
%configure2_5x
%make

%install
rm -rf $RPM_BUILD_ROOT
%makeinstall_std

%clean
rm -rf $RPM_BUILD_ROOT

%if %mdkversion < 200900
%post -n %libname -p /sbin/ldconfig
%endif
%if %mdkversion < 200900
%postun -n %libname -p /sbin/ldconfig
%endif

%files -n %libname
%defattr(-,root,root)
%_libdir/libytnef.so.%{major}*

%files -n %develname
%defattr(-,root,root)
%doc ChangeLog
%_libdir/libytnef.so
%_libdir/libytnef.a
%_includedir/*.h



%changelog
* Mon May 02 2011 Oden Eriksson <oeriksson@mandriva.com> 1.5-6mdv2011.0
+ Revision: 661562
- mass rebuild

* Sun Nov 28 2010 Oden Eriksson <oeriksson@mandriva.com> 1.5-5mdv2011.0
+ Revision: 602625
- rebuild

* Tue Mar 16 2010 Oden Eriksson <oeriksson@mandriva.com> 1.5-4mdv2010.1
+ Revision: 520974
- rebuilt for 2010.1

* Wed Sep 02 2009 Christophe Fergeau <cfergeau@mandriva.com> 1.5-3mdv2010.0
+ Revision: 425976
- rebuild

* Tue Jun 17 2008 Thierry Vignaud <tv@mandriva.org> 1.5-2mdv2009.0
+ Revision: 223093
- rebuild
- kill re-definition of %%buildroot on Pixel's request

  + Pixel <pixel@mandriva.com>
    - do not call ldconfig in %%post/%%postun, it is now handled by filetriggers

  + Olivier Blin <oblin@mandriva.com>
    - restore BuildRoot

* Mon Oct 29 2007 Götz Waschk <waschk@mandriva.org> 1.5-1mdv2008.1
+ Revision: 103034
- import libytnef


* Mon Oct 29 2007 Götz Waschk <waschk@mandriva.org> 1.5-1mdv2008.1
- initial package
