%define name libytnef
%define version 1.5
%define release %mkrel 1

%define major 0
%define libname %mklibname ytnef %major
%define develname %mklibname -d ytnef

Summary: TNEF Stream Parser Library
Name: %{name}
Version: %{version}
Release: %{release}
Source0: http://downloads.sourceforge.net/ytnef/%{name}-%{version}.tar.bz
License: GPLv2+
Group: System/Libraries
Url: http://ytnef.sourceforge.net/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot

%description
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %libname
Summary: TNEF Stream Parser shared library
Group: System/Libraries

%description -n %libname
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.

%package -n %develname
Summary: TNEF Stream Parser library
Group: Development/C
Requires: %libname = %version
Provides: libytnef-devel = %version-%release

%description -n %develname
TNEF Stream Parser Library to decode TNEF (winmail.dat) streams
generated by Microsoft Outlook.


%prep
%setup -q

%build
%configure2_5x
%make

%install
rm -rf $RPM_BUILD_ROOT
%makeinstall_std

%clean
rm -rf $RPM_BUILD_ROOT

%post -n %libname -p /sbin/ldconfig
%postun -n %libname -p /sbin/ldconfig

%files -n %libname
%defattr(-,root,root)
%_libdir/libytnef.so.%{major}*

%files -n %develname
%defattr(-,root,root)
%doc ChangeLog
%_libdir/libytnef.so
%_libdir/libytnef.a
%_libdir/libytnef.la
%_includedir/*.h

